[project]
name = "ai-workout-trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aider-chat>=0.56.0",
    "groq>=0.11.0",
    "ipykernel>=6.29.5",
    "ruff>=0.6.4",
]
